<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>VibertemisManager.Core</AssemblyName>
    <RootNamespace>VibertemisManager.Core</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/Integrity/*.bin" Condition="Exists('Resources/Integrity')" />
    <InternalsVisibleTo Include="VibertemisManager.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../update/public-key.pem" LogicalName="Vibertemis.Update.PublicKey" />
    <EmbeddedResource Include="Resources/VR/default-session.json" LogicalName="Vibertemis.VR.DefaultSession" />
  </ItemGroup>
</Project>
