#!/usr/bin/env python3
"""Regression harness for the focus resume path in xr_renderer.c.

Lifts the real handleSessionStateChange, releaseHostButtons, disarmHand,
resetInputState and applyPendingInputResume bodies out of the generated renderer
and compiles them against the host with a mock runtime, so what is under test is
the shipped code rather than a copy of it.

    python3 test_input_resume.py --source <xr_renderer.c> --headers <openxr/include>
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "..", "..", ".."))
DEFAULT_SOURCE = os.path.join(REPO, "build", "quest", "upstream", "app", "src",
                              "main", "jni", "xr-renderer", "xr_renderer.c")
HEADER_GUESSES = (
    os.path.join("build", "quest", "upstream", "app", "src", "main", "jni", "openxr", "include"),
    os.path.join("build", "quest", "upstream", "app", "src", "main", "jni", "include"),
    os.path.join("third_party", "openxr", "include"),
    os.path.join("openxr", "include"),
)

# Grabbing the counts and the grab modes out of the renderer rather than
# repeating them, so a source added or a mode renamed does not leave the
# harness quietly testing the wrong number of things.
HARNESS = "test_input_resume"
DEFINES = (("HAND_COUNT", "__HAND_COUNT__"),
           ("SRC_COUNT", "__SRC_COUNT__"),
           ("GRAB_NONE", "__GRAB_NONE__"),
           ("GRAB_MOVE", "__GRAB_MOVE__"))

# The lifted functions, in the order they depend on each other: the session
# handler, the two functions that take a hand's press away, the whole-context
# reset that calls disarmHand, and the resume that calls resetInputState.
FUNCTIONS = (("handleSessionStateChange", r"^static\s+void\s+handleSessionStateChange\s*\("),
             ("releaseHostButtons", r"^static\s+void\s+releaseHostButtons\s*\("),
             ("disarmHand", r"^static\s+void\s+disarmHand\s*\("),
             ("resetInputState", r"^static\s+void\s+resetInputState\s*\("),
             ("applyPendingInputResume", r"^static\s+int\s+applyPendingInputResume\s*\("))

PREAMBLE = r'''
/* Generated by quest/native/tests/test_input_resume.py. The functions between
   the preamble and main are the real ones, lifted out of the generated
   xr_renderer.c at run time. Nothing here reimplements them. */
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include <openxr/openxr.h>

#define HAND_LEFT  0
#define HAND_RIGHT 1
#define HAND_COUNT __HAND_COUNT__
#define SRC_COUNT  __SRC_COUNT__
#define GRAB_NONE  __GRAB_NONE__
#define GRAB_MOVE  __GRAB_MOVE__

#define VR_BUTTON_LEFT  0x1
#define VR_BUTTON_RIGHT 0x2

/* A euro filter state. The reset drops the history by clearing the flag, and
   that is the only part of one these functions touch, so that is all there is
   here. */
typedef struct { int valid; } EuroState;

/* Only the fields the lifted functions read or write, plus the two settings
   the reset has to leave where they are. */
typedef struct {
    XrSession session;
    XrSessionState sessionState;
    int sessionRunning;
    int exitRequested;
    int inputResumePending;

    int buttonsDown;
    int hostOwner;
    int hostReleasePending;
    float scrollCarry;
    long lastInputNs;

    int inputArmed[HAND_COUNT];
    int triggerDown[SRC_COUNT];
    int triggerEdge[SRC_COUNT];
    int triggerSwallowed[SRC_COUNT];
    int pinchSwallowed[SRC_COUNT];
    int lockArmed[SRC_COUNT];
    int gripEdge[SRC_COUNT];
    int grabDown[SRC_COUNT];
    int poseSeen[SRC_COUNT];
    XrPosef lastAim[SRC_COUNT];

    int jointPinch[HAND_COUNT];
    int handClick[HAND_COUNT];
    int handClickBlocked[HAND_COUNT];
    int handTracked[HAND_COUNT];
    int handRayValid[HAND_COUNT];
    int pinchPointValid[HAND_COUNT];

    EuroState filterU;
    EuroState filterV;
    EuroState aimFilterPos[HAND_COUNT][3];
    EuroState aimFilterRot[HAND_COUNT];

    int pointerAwake;
    float stillFor;
    float movingFor;
    int beamVisible;
    int grabMode;
    int poseDirty;
    int kbKeyDown;

    /* The user's own choices, which are not input state */
    int pointerOn;
    int handsLocked;
} XrCtx;

static int g_marker;
static int g_beginCalls;
static int g_endCalls;
static int g_failSet;
static char g_fail[192];
static XrViewConfigurationType g_beginViewConfig;

static void mockFail(const char* what) {
    if (!g_failSet) {
        snprintf(g_fail, sizeof(g_fail), "%s", what);
        g_failSet = 1;
    }
}

/* Stands in for the two session calls handleSessionStateChange makes, and
   records what it asked for. */
XrResult xrBeginSession(XrSession session, const XrSessionBeginInfo* beginInfo) {
    g_beginCalls++;
    if (session == XR_NULL_HANDLE) {
        mockFail("xrBeginSession on a null session");
        return XR_ERROR_HANDLE_INVALID;
    }
    if (beginInfo == NULL) {
        mockFail("xrBeginSession with no begin info");
        return XR_ERROR_VALIDATION_FAILURE;
    }
    g_beginViewConfig = beginInfo->primaryViewConfigurationType;
    return XR_SUCCESS;
}

XrResult xrEndSession(XrSession session) {
    g_endCalls++;
    if (session == XR_NULL_HANDLE) {
        mockFail("xrEndSession on a null session");
        return XR_ERROR_HANDLE_INVALID;
    }
    return XR_SUCCESS;
}

/* The renderer's own checkXr, without the Android log behind it. */
static int checkXr(XrResult res, const char* what) {
    if (XR_FAILED(res)) {
        printf("checkXr: %s failed: %d\n", what, (int)res);
        return 0;
    }
    return 1;
}

static void mockLog(const char* fmt, ...) {
    va_list args;
    va_start(args, fmt);
    vprintf(fmt, args);
    va_end(args);
    putchar('\n');
}

#define LOGI(...) mockLog(__VA_ARGS__)

/* Test setup, not code under test: the input state a session whose focus went
   away leaves standing, which no frame between the loss and the gain will have
   looked at. */
static void seedHeld(XrCtx* ctx) {
    int h, s, a;

    /* An asleep pointer on stale timers, and a clock from before the gap */
    ctx->pointerAwake = 0;
    ctx->stillFor = 9.0f;
    ctx->movingFor = 2.5f;
    ctx->beamVisible = 1;
    ctx->lastInputNs = 1234567890L;
    ctx->scrollCarry = 0.75f;
    ctx->kbKeyDown = 1;

    /* A press at the host and the hand that owns it */
    ctx->buttonsDown = VR_BUTTON_LEFT | VR_BUTTON_RIGHT;
    ctx->hostOwner = HAND_RIGHT;
    ctx->hostReleasePending = 0;

    /* Both hands armed, both holding a pinch, with their filter history */
    for (h = 0; h < HAND_COUNT; h++) {
        ctx->inputArmed[h] = 1;
        ctx->handTracked[h] = 1;
        ctx->handClick[h] = 1;
        ctx->handClickBlocked[h] = 1;
        ctx->jointPinch[h] = 1;
        ctx->handRayValid[h] = 1;
        ctx->pinchPointValid[h] = 1;
        ctx->aimFilterRot[h].valid = 1;
        for (a = 0; a < 3; a++) {
            ctx->aimFilterPos[h][a].valid = 1;
        }
    }
    for (s = 0; s < SRC_COUNT; s++) {
        ctx->triggerDown[s] = 1;
        ctx->triggerEdge[s] = 1;
        ctx->triggerSwallowed[s] = 1;
        ctx->pinchSwallowed[s] = 1;
        ctx->lockArmed[s] = 1;
        ctx->gripEdge[s] = 1;
        ctx->grabDown[s] = 1;
        ctx->poseSeen[s] = 1;
        ctx->lastAim[s].position.x = 0.5f;
        ctx->lastAim[s].orientation.w = 1.0f;
    }

    /* The cursor's own filter, and a drag in progress on a pose that is not
       marked stale yet */
    ctx->filterU.valid = 1;
    ctx->filterV.valid = 1;
    ctx->grabMode = GRAB_MOVE;
    ctx->poseDirty = 0;

    /* The user's own choices */
    ctx->pointerOn = 0;
    ctx->handsLocked = 1;
}

/* The same on a context whose session fields the caller is about to set. */
static void seedUnattended(XrCtx* ctx) {
    memset(ctx, 0, sizeof(*ctx));
    ctx->session = (XrSession)(void*)&g_marker;
    seedHeld(ctx);
}
'''

MAIN = r'''
#define CHECK(cond) do { \
    if (!(cond)) { \
        fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        if (g_failSet) fprintf(stderr, "  runtime mock: %s\n", g_fail); \
        return 1; \
    } \
} while (0)

/* Everything a spent resume is expected to have dropped, so each case below
   asserts the same set. */
static int checkCleared(XrCtx* ctx) {
    int h, s, a;

    CHECK(ctx->inputResumePending == 0);
    CHECK(ctx->buttonsDown == 0);
    CHECK(ctx->hostOwner == -1);
    for (h = 0; h < HAND_COUNT; h++) {
        CHECK(ctx->inputArmed[h] == 0);
        CHECK(ctx->handTracked[h] == 0);
        CHECK(ctx->handClick[h] == 0);
        CHECK(ctx->handClickBlocked[h] == 0);
        CHECK(ctx->jointPinch[h] == 0);
        CHECK(ctx->handRayValid[h] == 0);
        CHECK(ctx->pinchPointValid[h] == 0);
        CHECK(ctx->aimFilterRot[h].valid == 0);
        for (a = 0; a < 3; a++) {
            CHECK(ctx->aimFilterPos[h][a].valid == 0);
        }
    }
    for (s = 0; s < SRC_COUNT; s++) {
        CHECK(ctx->triggerDown[s] == 0);
        CHECK(ctx->triggerEdge[s] == 0);
        CHECK(ctx->triggerSwallowed[s] == 0);
        CHECK(ctx->pinchSwallowed[s] == 0);
        CHECK(ctx->lockArmed[s] == 0);
        CHECK(ctx->gripEdge[s] == 0);
        CHECK(ctx->grabDown[s] == 0);
        CHECK(ctx->poseSeen[s] == 0);
        CHECK(ctx->lastAim[s].position.x == 0.0f);
        CHECK(ctx->lastAim[s].position.y == 0.0f);
        CHECK(ctx->lastAim[s].position.z == 0.0f);
        CHECK(ctx->lastAim[s].orientation.x == 0.0f);
        CHECK(ctx->lastAim[s].orientation.y == 0.0f);
        CHECK(ctx->lastAim[s].orientation.z == 0.0f);
        CHECK(ctx->lastAim[s].orientation.w == 0.0f);
    }
    CHECK(ctx->filterU.valid == 0);
    CHECK(ctx->filterV.valid == 0);
    CHECK(ctx->scrollCarry == 0.0f);
    CHECK(ctx->lastInputNs == 0);
    CHECK(ctx->kbKeyDown == 0);
    return 0;
}

/* A frame that is not a resume has to leave all of that standing, and must not
   queue a release of its own. */
static int checkUntouched(XrCtx* ctx) {
    int h, s, a;

    CHECK(ctx->buttonsDown == (VR_BUTTON_LEFT | VR_BUTTON_RIGHT));
    CHECK(ctx->hostOwner == HAND_RIGHT);
    CHECK(ctx->hostReleasePending == 0);
    CHECK(ctx->pointerAwake == 0);
    CHECK(ctx->stillFor == 9.0f);
    CHECK(ctx->movingFor == 2.5f);
    CHECK(ctx->beamVisible == 1);
    CHECK(ctx->lastInputNs == 1234567890L);
    CHECK(ctx->scrollCarry == 0.75f);
    CHECK(ctx->kbKeyDown == 1);
    CHECK(ctx->grabMode == GRAB_MOVE);
    CHECK(ctx->poseDirty == 0);
    CHECK(ctx->filterU.valid == 1);
    CHECK(ctx->filterV.valid == 1);
    for (h = 0; h < HAND_COUNT; h++) {
        CHECK(ctx->inputArmed[h] == 1);
        CHECK(ctx->handTracked[h] == 1);
        CHECK(ctx->handClick[h] == 1);
        CHECK(ctx->handClickBlocked[h] == 1);
        CHECK(ctx->jointPinch[h] == 1);
        CHECK(ctx->handRayValid[h] == 1);
        CHECK(ctx->pinchPointValid[h] == 1);
        CHECK(ctx->aimFilterRot[h].valid == 1);
        for (a = 0; a < 3; a++) {
            CHECK(ctx->aimFilterPos[h][a].valid == 1);
        }
    }
    for (s = 0; s < SRC_COUNT; s++) {
        CHECK(ctx->triggerDown[s] == 1);
        CHECK(ctx->triggerEdge[s] == 1);
        CHECK(ctx->triggerSwallowed[s] == 1);
        CHECK(ctx->pinchSwallowed[s] == 1);
        CHECK(ctx->lockArmed[s] == 1);
        CHECK(ctx->gripEdge[s] == 1);
        CHECK(ctx->grabDown[s] == 1);
        CHECK(ctx->poseSeen[s] == 1);
        CHECK(ctx->lastAim[s].position.x == 0.5f);
        CHECK(ctx->lastAim[s].orientation.w == 1.0f);
    }
    return 0;
}

int main(void) {
    XrCtx ctx;

    /* The rest of the session handler, so the runtime calls it makes are
       exercised rather than only linked. None of it is a resume. */
    memset(&ctx, 0, sizeof(ctx));
    ctx.session = (XrSession)(void*)&g_marker;
    handleSessionStateChange(&ctx, XR_SESSION_STATE_READY);
    CHECK(ctx.sessionState == XR_SESSION_STATE_READY);
    CHECK(g_beginCalls == 1);
    CHECK(g_beginViewConfig == XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO);
    CHECK(ctx.sessionRunning == 1);
    CHECK(ctx.inputResumePending == 0);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_STOPPING);
    CHECK(g_endCalls == 1);
    CHECK(ctx.sessionRunning == 0);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_EXITING);
    CHECK(ctx.exitRequested == 1);
    CHECK(ctx.sessionRunning == 0);
    CHECK(ctx.inputResumePending == 0);
    CHECK(g_failSet == 0);

    /* Focus arriving from visible queues the resume, and the frame that spends
       it drops everything the unattended gap left standing. */
    seedUnattended(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_VISIBLE);
    CHECK(ctx.sessionState == XR_SESSION_STATE_VISIBLE);
    CHECK(ctx.inputResumePending == 0);
    /* Nothing is dropped on the way out of focus: the flag is the only record
       that input went unattended, and the reset waits for the way back. */
    CHECK(applyPendingInputResume(&ctx) == 0);
    CHECK(checkUntouched(&ctx) == 0);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.sessionState == XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 1);
    CHECK(applyPendingInputResume(&ctx) == 1);
    CHECK(checkCleared(&ctx) == 0);
    /* The release still has to reach Java, on the frame the buttons came up. */
    CHECK(ctx.hostReleasePending == 1);
    /* The pointer wakes rather than waiting out the movement gate again, and a
       grab interrupted by the gap is over rather than stale. */
    CHECK(ctx.pointerAwake == 1);
    CHECK(ctx.stillFor == 0.0f);
    CHECK(ctx.movingFor == 0.0f);
    CHECK(ctx.beamVisible == 0);
    CHECK(ctx.grabMode == GRAB_NONE);
    CHECK(ctx.poseDirty == 1);
    /* Pointing turned off and the hands locked out are the user's own choices,
       so a resume must not undo them. */
    CHECK(ctx.pointerOn == 0);
    CHECK(ctx.handsLocked == 1);

    /* Focus is in force and the flag was spent above. The same state arriving
       again is not another resume, and the next normal frame drops nothing. */
    seedHeld(&ctx);
    CHECK(ctx.sessionState == XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 0);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 0);
    CHECK(applyPendingInputResume(&ctx) == 0);
    CHECK(checkUntouched(&ctx) == 0);

    /* A loss and a gain inside one pollEvents batch leave no unfocused frame
       behind to release on, so the flag has to carry the reset by itself. */
    seedUnattended(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 1);
    CHECK(applyPendingInputResume(&ctx) == 1);
    CHECK(checkCleared(&ctx) == 0);
    seedHeld(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_VISIBLE);
    CHECK(ctx.inputResumePending == 0);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 1);
    CHECK(applyPendingInputResume(&ctx) == 1);
    CHECK(checkCleared(&ctx) == 0);
    CHECK(ctx.hostReleasePending == 1);
    /* And it is spent, so the frame after this one is an ordinary frame. */
    CHECK(applyPendingInputResume(&ctx) == 0);

    /* A resume noticed while focus is elsewhere stays pending rather than
       being thrown away, since it is all the record of the gap there is. */
    seedUnattended(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 1);
    seedHeld(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_VISIBLE);
    CHECK(ctx.inputResumePending == 1);
    /* Not focused, so no input is enabled and nothing is spent. */
    CHECK(applyPendingInputResume(&ctx) == 0);
    CHECK(ctx.inputResumePending == 1);
    CHECK(checkUntouched(&ctx) == 0);
    /* The next frame with focus in force spends it, and drops the held state
       even though the gain queued nothing new. */
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    CHECK(ctx.inputResumePending == 1);
    CHECK(applyPendingInputResume(&ctx) == 1);
    CHECK(checkCleared(&ctx) == 0);
    CHECK(ctx.hostReleasePending == 1);

    /* A pinch held across the gap is not a press the user could have seen, so
       both hands come back with nothing trusted on either side. */
    seedUnattended(&ctx);
    handleSessionStateChange(&ctx, XR_SESSION_STATE_FOCUSED);
    ctx.inputArmed[HAND_LEFT] = 0;
    ctx.inputArmed[HAND_RIGHT] = 0;
    CHECK(ctx.jointPinch[HAND_RIGHT] == 1);
    CHECK(ctx.handClick[HAND_RIGHT] == 1);
    CHECK(applyPendingInputResume(&ctx) == 1);
    CHECK(ctx.inputArmed[HAND_LEFT] == 0);
    CHECK(ctx.inputArmed[HAND_RIGHT] == 0);
    CHECK(ctx.jointPinch[HAND_RIGHT] == 0);
    CHECK(ctx.handClick[HAND_RIGHT] == 0);
    CHECK(checkCleared(&ctx) == 0);
    CHECK(ctx.hostReleasePending == 1);
    CHECK(g_failSet == 0);

    printf("input resume: ok\n");
    return 0;
}
'''


def grab_function(source, pattern, name, path):
    start = re.search(pattern, source, re.M)
    if start is None:
        sys.exit("%s: %s not found in %s" % (HARNESS, name, path))
    end = re.search(r"^\}", source[start.end():], re.M)
    if end is None:
        sys.exit("%s: end of %s not found in %s" % (HARNESS, name, path))
    return source[start.start():start.end() + end.end()]


def grab_define(source, name, path):
    m = re.search(r"^#define\s+%s\s+(.+?)\s*$" % re.escape(name), source, re.M)
    if m is None:
        sys.exit("%s: #define %s not found in %s" % (HARNESS, name, path))
    return m.group(1)


def find_headers(given):
    if given:
        return given
    for rel in HEADER_GUESSES:
        path = os.path.join(REPO, rel)
        if os.path.exists(os.path.join(path, "openxr", "openxr.h")):
            return path
    sys.exit("%s: pass --headers <dir holding openxr/openxr.h>" % HARNESS)


def main():
    ap = argparse.ArgumentParser(description="compile the real focus resume "
                                                 "functions and run them")
    ap.add_argument("--source", default=DEFAULT_SOURCE,
                    help="generated xr_renderer.c to lift the functions out of")
    ap.add_argument("--headers", help="include dir holding openxr/openxr.h")
    ap.add_argument("--cc", default=os.environ.get("CC", "cc"),
                    help="host C compiler (default: $CC or cc)")
    args = ap.parse_args()

    headers = find_headers(args.headers)
    with open(args.source) as handle:
        source = handle.read()

    harness = PREAMBLE
    for name, placeholder in DEFINES:
        harness = harness.replace(placeholder, grab_define(source, name, args.source))
    for name, pattern in FUNCTIONS:
        harness += "\n" + grab_function(source, pattern, name, args.source)
    harness += MAIN

    with tempfile.TemporaryDirectory() as tmp:
        c_path = os.path.join(tmp, "harness.c")
        exe = os.path.join(tmp, "harness")
        with open(c_path, "w") as handle:
            handle.write(harness)

        build = subprocess.run([args.cc, "-std=c11", "-Wall", "-Werror",
                                "-I", headers, c_path, "-o", exe],
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               universal_newlines=True)
        if build.returncode != 0:
            sys.stdout.write(build.stdout)
            return build.returncode

        run = subprocess.run([exe], stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             universal_newlines=True)
        sys.stdout.write(run.stdout)
        return run.returncode


if __name__ == "__main__":
    sys.exit(main())
