#!/usr/bin/env python3
"""Regression harness for the flat hand tracking path in xr_renderer.c.

Lifts the real poseUsable and sampleHand bodies out of the generated renderer
and compiles them against the host with a mock runtime, so what is under test
is the shipped code rather than a copy of it.

    python3 test_flat_tracking.py --source <xr_renderer.c> --headers <openxr/include>
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "..", "..", ".."))
DEFAULT_SOURCE = os.path.join(REPO, "build", "quest", "upstream", "app", "src",
                              "main", "jni", "xr-renderer", "xr_renderer.c")
HEADER_GUESSES = (
    os.path.join("build", "quest", "upstream", "app", "src", "main", "jni", "openxr", "include"),
    os.path.join("build", "quest", "upstream", "app", "src", "main", "jni", "include"),
    os.path.join("third_party", "openxr", "include"),
    os.path.join("openxr", "include"),
)

PREAMBLE = r'''
/* Generated by quest/native/tests/test_flat_tracking.py. The functions
   between the preamble and main are the real ones, lifted out of the
   generated xr_renderer.c at run time. Nothing here reimplements them. */
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

/* Ask for the two extensions before the headers are read, so the mock fills
   the same structs the renderer builds the chain out of. */
#ifndef XR_EXT_hand_tracking
#define XR_EXT_hand_tracking 1
#endif
#ifndef XR_FB_hand_tracking_aim
#define XR_FB_hand_tracking_aim 1
#endif
#include <openxr/openxr.h>

#define HAVE_FB_HAND_TRACKING_AIM 1
#define HAND_LEFT  0
#define HAND_RIGHT 1
#define HAND_COUNT 2
#define PINCH_ON_M  __PINCH_ON__
#define PINCH_OFF_M __PINCH_OFF__

typedef struct { float x, y, z; } Vec3;

/* Only the fields sampleHand and releaseHostButtons read. */
typedef struct {
    XrTime predictedDisplayTime;
    PFN_xrLocateHandJointsEXT pfnLocateHandJoints;
    int jointTracking;
    int handAim;
    XrHandTrackerEXT handTrackers[HAND_COUNT];
    int handTracked[HAND_COUNT];
    int handClick[HAND_COUNT];
    int handClickBlocked[HAND_COUNT];
    int jointPinch[HAND_COUNT];
    Vec3 pinchPoint[HAND_COUNT];
    int pinchPointValid[HAND_COUNT];
    XrPosef handRay[HAND_COUNT];
    int handRayValid[HAND_COUNT];
    int hostOwner;
    int buttonsDown;
    int hostReleasePending;
} XrCtx;

static int g_marker;
static int g_locateCount;
static int g_failSet;
static char g_fail[192];
static XrBool32 g_active;
static XrHandTrackingAimFlagsFB g_status;
static float g_aimX;
static int g_tipsValid;
static float g_tipY;

static void mockFail(const char* what) {
    if (!g_failSet) {
        snprintf(g_fail, sizeof(g_fail), "%s", what);
        g_failSet = 1;
    }
}

static XrHandTrackingAimFlagsFB aimStatus(int computed, int valid, int pinch, int gesture) {
    XrHandTrackingAimFlagsFB s = 0;
    if (computed) s |= XR_HAND_TRACKING_AIM_COMPUTED_BIT_FB;
    if (valid) s |= XR_HAND_TRACKING_AIM_VALID_BIT_FB;
    if (pinch) s |= XR_HAND_TRACKING_AIM_INDEX_PINCHING_BIT_FB;
    if (gesture) s |= XR_HAND_TRACKING_AIM_SYSTEM_GESTURE_BIT_FB;
    return s;
}

/* Stands in for xrLocateHandJointsEXT. */
static XrResult mockLocate(XrHandTrackerEXT tracker,
                           const XrHandJointsLocateInfoEXT* locate,
                           XrHandJointLocationsEXT* locations) {
    (void)tracker;
    (void)locate;
    g_locateCount++;
    if (locations == NULL || locations->jointLocations == NULL) {
        mockFail("no joint buffer in the locate");
        return XR_SUCCESS;
    }
    for (uint32_t i = 0; i < locations->jointCount; i++) {
        XrHandJointLocationEXT* j = &locations->jointLocations[i];
        j->locationFlags = 0;
        j->pose.orientation.x = 0.0f;
        j->pose.orientation.y = 0.0f;
        j->pose.orientation.z = 0.0f;
        j->pose.orientation.w = 1.0f;
        j->pose.position.x = 0.0f;
        j->pose.position.y = 0.0f;
        j->pose.position.z = 0.0f;
    }
    if (g_tipsValid) {
        /* Thumb and index 10 mm apart, so inside PINCH_ON_M either way. */
        XrHandJointLocationEXT* thumb =
                &locations->jointLocations[XR_HAND_JOINT_THUMB_TIP_EXT];
        XrHandJointLocationEXT* index =
                &locations->jointLocations[XR_HAND_JOINT_INDEX_TIP_EXT];
        thumb->locationFlags |= XR_SPACE_LOCATION_POSITION_VALID_BIT;
        index->locationFlags |= XR_SPACE_LOCATION_POSITION_VALID_BIT;
        thumb->pose.position.x = 0.10f;
        thumb->pose.position.y = g_tipY;
        thumb->pose.position.z = -0.30f;
        index->pose.position.x = 0.11f;
        index->pose.position.y = g_tipY;
        index->pose.position.z = -0.30f;
    }

    /* The aim state has to arrive on the tail of the locations chain, and a
       next pointing back at the head is a cycle the runtime would walk. */
    if (locations->next == NULL) {
        mockFail("aim state missing from the locate chain");
    }
    else {
        XrHandTrackingAimStateFB* aim = (XrHandTrackingAimStateFB*)locations->next;
        if (aim->type != XR_TYPE_HAND_TRACKING_AIM_STATE_FB) {
            mockFail("chain tail is not the FB aim state");
        }
        if (aim->next != NULL) {
            mockFail("aim state next is not null, the chain is cyclic");
        }
        aim->status = g_status;
        aim->aimPose.orientation.x = 0.0f;
        aim->aimPose.orientation.y = 0.0f;
        aim->aimPose.orientation.z = 0.0f;
        aim->aimPose.orientation.w = 1.0f;
        aim->aimPose.position.x = g_aimX;
        aim->aimPose.position.y = 0.10f;
        aim->aimPose.position.z = -0.50f;
    }
    locations->isActive = g_active;
    return XR_SUCCESS;
}

/* Stand-in for the ray the renderer builds itself, which only runs where the
   aim extension is not in use. It marks the fallback as having happened, so a
   test can tell no ray from our ray. */
static void buildHandRay(XrCtx* ctx, int hand, const XrPosef* head,
                         const XrHandJointLocationEXT* joints) {
    (void)head;
    (void)joints;
    ctx->handRayValid[hand] = 1;
    ctx->handRay[hand].position.x = -999.0f;
}
'''

MAIN = r'''
#define CHECK(cond) do { \
    if (!(cond)) { \
        fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        if (g_failSet) fprintf(stderr, "  runtime mock: %s\n", g_fail); \
        return 1; \
    } \
} while (0)

int main(void) {
    XrCtx ctx;
    XrPosef pose = { .orientation = { 0.0f, 0.0f, 0.0f, 1.0f },
                     .position = { 0.0f, 0.0f, 0.0f } };
    /* A usable head pose, so a fallback ray would be built if one were tried. */
    XrPosef head = { .orientation = { 0.0f, 0.0f, 0.0f, 1.0f },
                     .position = { 0.0f, 1.60f, 0.0f } };
    XrSpace space = (XrSpace)(void*)&g_marker;
    int click, i;

    /* poseUsable: nothing unusable reaches the filters. */
    pose.position.x = NAN;
    CHECK(poseUsable(&pose) == 0);
    pose.position.x = 0.0f;
    pose.orientation.y = NAN;
    CHECK(poseUsable(&pose) == 0);
    pose.orientation.y = 0.0f;
    pose.position.z = INFINITY;
    CHECK(poseUsable(&pose) == 0);
    pose.position.z = 0.0f;
    pose.orientation = (XrQuaternionf){ 0.0f, 0.0f, 0.0f, 0.0f };
    CHECK(poseUsable(&pose) == 0);
    /* Squaring FLT_MAX overflows, so the length is not a length. */
    pose.orientation = (XrQuaternionf){ FLT_MAX, FLT_MAX, FLT_MAX, FLT_MAX };
    CHECK(poseUsable(&pose) == 0);
    /* A good pose is taken and left on the unit sphere. */
    pose.orientation = (XrQuaternionf){ 0.0f, 0.0f, 2.0f, 0.0f };
    CHECK(poseUsable(&pose) == 1);
    CHECK(fabsf(pose.orientation.z) == 1.0f);

    memset(&ctx, 0, sizeof(ctx));
    ctx.jointTracking = 1;
    ctx.handAim = 1;
    ctx.predictedDisplayTime = 1000;
    ctx.pfnLocateHandJoints = mockLocate;
    ctx.handTrackers[HAND_RIGHT] = (XrHandTrackerEXT)(void*)&g_marker;
    g_locateCount = 0;
    g_active = XR_TRUE;
    g_tipsValid = 1;
    g_tipY = 0.20f;

    /* releaseHostButtons: only the owning hand can let go, the owner goes to
       -1, and letting go again does not queue a second release. */
    ctx.hostOwner = HAND_RIGHT;
    ctx.buttonsDown = 1;
    ctx.hostReleasePending = 0;
    releaseHostButtons(&ctx, HAND_LEFT);
    CHECK(ctx.hostOwner == HAND_RIGHT);
    CHECK(ctx.buttonsDown == 1);
    CHECK(ctx.hostReleasePending == 0);
    releaseHostButtons(&ctx, HAND_RIGHT);
    CHECK(ctx.hostOwner == -1);
    CHECK(ctx.buttonsDown == 0);
    CHECK(ctx.hostReleasePending == 1);
    releaseHostButtons(&ctx, HAND_RIGHT);
    CHECK(ctx.hostOwner == -1);
    CHECK(ctx.buttonsDown == 0);
    CHECK(ctx.hostReleasePending == 1);
    /* Back to the state memset above leaves, for the sampleHand cases. */
    ctx.hostOwner = 0;
    ctx.buttonsDown = 0;
    ctx.hostReleasePending = 0;

    /* A held pinch still samples every frame, and the ray follows the aim. */
    g_status = aimStatus(1, 1, 1, 0);
    g_aimX = 0.25f;
    click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
    CHECK(g_locateCount == 1);
    CHECK(g_failSet == 0);
    CHECK(click == 1);
    CHECK(ctx.handClick[HAND_RIGHT] == 1);
    CHECK(ctx.jointPinch[HAND_RIGHT] == 1);
    CHECK(ctx.handTracked[HAND_RIGHT] == 1);
    CHECK(ctx.handRayValid[HAND_RIGHT] == 1);
    CHECK(ctx.handRay[HAND_RIGHT].position.x == 0.25f);
    CHECK(ctx.pinchPointValid[HAND_RIGHT] == 1);
    CHECK(fabsf(ctx.pinchPoint[HAND_RIGHT].x - 0.105f) < 1e-4f);

    g_aimX = 0.75f;
    click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
    CHECK(g_locateCount == 2);
    CHECK(g_failSet == 0);
    CHECK(click == 1);
    CHECK(ctx.handRayValid[HAND_RIGHT] == 1);
    CHECK(ctx.handRay[HAND_RIGHT].position.x == 0.75f);

    /* Joints that did not answer clear what the last frame left standing. */
    g_active = XR_FALSE;
    ctx.handRayValid[HAND_RIGHT] = 1;
    ctx.pinchPointValid[HAND_RIGHT] = 1;
    ctx.jointPinch[HAND_RIGHT] = 1;
    ctx.handClick[HAND_RIGHT] = 1;
    click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
    CHECK(click == 0);
    CHECK(ctx.handRayValid[HAND_RIGHT] == 0);
    CHECK(ctx.pinchPointValid[HAND_RIGHT] == 0);
    CHECK(ctx.jointPinch[HAND_RIGHT] == 0);
    CHECK(ctx.handClick[HAND_RIGHT] == 0);
    CHECK(ctx.handTracked[HAND_RIGHT] == 0);

    /* A gesture the system owns takes the ray and the click with it. */
    g_active = XR_TRUE;
    g_status = aimStatus(1, 1, 0, 1);
    ctx.handRayValid[HAND_RIGHT] = 1;
    ctx.jointPinch[HAND_RIGHT] = 1;
    click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
    CHECK(click == 0);
    CHECK(ctx.handRayValid[HAND_RIGHT] == 0);
    CHECK(ctx.handClick[HAND_RIGHT] == 0);
    CHECK(ctx.handClickBlocked[HAND_RIGHT] == 1);
    CHECK(ctx.jointPinch[HAND_RIGHT] == 0);

    /* An aim state the runtime has not computed falls back to nothing: the
       stub ray would have shown up as handRayValid, so this is the check. */
    for (i = 0; i < 2; i++) {
        g_status = (i == 0) ? aimStatus(1, 0, 0, 0) : aimStatus(0, 0, 0, 0);
        ctx.handRayValid[HAND_RIGHT] = 1;
        click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
        CHECK(click == 0);
        CHECK(ctx.handRayValid[HAND_RIGHT] == 0);
        CHECK(ctx.handClick[HAND_RIGHT] == 0);
        CHECK(ctx.handClickBlocked[HAND_RIGHT] == 1);
        CHECK(ctx.jointPinch[HAND_RIGHT] == 0);
    }

    /* A fingertip that came back NaN is not a pinch point, aim or not. */
    g_status = aimStatus(1, 1, 1, 0);
    g_tipY = NAN;
    click = sampleHand(&ctx, HAND_RIGHT, space, &head, 1);
    CHECK(click == 1);
    CHECK(ctx.pinchPointValid[HAND_RIGHT] == 0);
    CHECK(ctx.handRayValid[HAND_RIGHT] == 1);
    CHECK(ctx.handClick[HAND_RIGHT] == 1);

    printf("flat tracking: ok\n");
    return 0;
}
'''


def grab_function(source, pattern, name, path):
    start = re.search(pattern, source, re.M)
    if start is None:
        sys.exit("test_flat_tracking: %s not found in %s" % (name, path))
    end = re.search(r"^\}", source[start.end():], re.M)
    if end is None:
        sys.exit("test_flat_tracking: end of %s not found in %s" % (name, path))
    return source[start.start():start.end() + end.end()]


def grab_define(source, name, path):
    m = re.search(r"^#define\s+%s\s+(\S+)" % re.escape(name), source, re.M)
    if m is None:
        sys.exit("test_flat_tracking: #define %s not found in %s" % (name, path))
    return m.group(1)


def find_headers(given):
    if given:
        return given
    for rel in HEADER_GUESSES:
        path = os.path.join(REPO, rel)
        if os.path.exists(os.path.join(path, "openxr", "openxr.h")):
            return path
    sys.exit("test_flat_tracking: pass --headers <dir holding openxr/openxr.h>")


def main():
    ap = argparse.ArgumentParser(description="compile the real hand tracking "
                                                 "functions and run them")
    ap.add_argument("--source", default=DEFAULT_SOURCE,
                    help="generated xr_renderer.c to lift the functions out of")
    ap.add_argument("--headers", help="include dir holding openxr/openxr.h")
    ap.add_argument("--cc", default=os.environ.get("CC", "cc"),
                    help="host C compiler (default: $CC or cc)")
    args = ap.parse_args()

    headers = find_headers(args.headers)
    with open(args.source) as handle:
        source = handle.read()

    harness = (PREAMBLE
               .replace("__PINCH_ON__", grab_define(source, "PINCH_ON_M", args.source))
               .replace("__PINCH_OFF__", grab_define(source, "PINCH_OFF_M", args.source))
               + "\n" + grab_function(source, r"^static\s+int\s+poseUsable\s*\(",
                                      "poseUsable", args.source)
               + "\n" + grab_function(source, r"^static\s+int\s+sampleHand\s*\(",
                                      "sampleHand", args.source)
               + "\n" + grab_function(source, r"^static\s+void\s+releaseHostButtons\s*\(",
                                      "releaseHostButtons", args.source)
               + MAIN)

    with tempfile.TemporaryDirectory() as tmp:
        c_path = os.path.join(tmp, "harness.c")
        exe = os.path.join(tmp, "harness")
        with open(c_path, "w") as handle:
            handle.write(harness)

        build = subprocess.run([args.cc, "-std=c11", "-Wall", "-Werror",
                                "-I", headers, c_path, "-o", exe, "-lm"],
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               universal_newlines=True)
        if build.returncode != 0:
            sys.stdout.write(build.stdout)
            return build.returncode

        run = subprocess.run([exe], stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             universal_newlines=True)
        sys.stdout.write(run.stdout)
        return run.returncode


if __name__ == "__main__":
    sys.exit(main())
