using System;
using System.IO;
using System.Threading;
using System.Windows.Forms;
using VibertemisManager.Core;
using VibertemisManager.Core.ALVR;
using VibertemisManager.Core.AutoStart;
using VibertemisManager.Core.Companion;
using VibertemisManager.Core.Firewall;
using VibertemisManager.Core.Integrity;
using VibertemisManager.Core.Network;
using VibertemisManager.Core.Paths;
using VibertemisManager.Core.Platform.Abstractions;
using VibertemisManager.Core.Platform.Windows;
using VibertemisManager.Core.Settings;
using VibertemisManager.Core.SingleInstance;
using VibertemisManager.Core.Steam;
using VibertemisManager.Core.Update;

namespace VibertemisManager.App;

internal static class Program
{
    public const string MutexName = "Local\\VibertemisVRHostManager";
    public const string CompanionMutexName = "Local\\VibertemisHostCompanion";

    [STAThread]
    public static int Main(string[] args)
    {
        // The --apply-update worker mode is detected BEFORE any
        // ApplicationConfiguration.Initialize, single-instance mutex,
        // settings store, integrity verifier, or service wiring. It
        // runs in a renamed copy of this same exe and must not
        // contend with the running manager over the app mutex.
        var applyUpdateJob = TryFindArgValue(args, "--apply-update");
        if (!string.IsNullOrEmpty(applyUpdateJob))
        {
            return RunApplyUpdate(applyUpdateJob);
        }

        var parsed = CliArgs.Parse(args);
        if (Array.Exists(args, a => a == "--verify-install"))
        {
            try
            {
                var install = new EnvironmentPathResolver();
                var integrity = IntegrityVerifier.FromEmbedded(typeof(Program).Assembly,
                    "VibertemisManager.App.Resources.Integrity.integrity.json", install.ProgramsRoot);
                foreach (var relative in InstalledPayload.RequiredPaths)
                    if (!integrity.Verify(Path.Combine(install.ProgramsRoot, relative), out _)) return 2;
                return 0;
            }
            catch { return 2; }
        }

        ApplicationConfiguration.Initialize();

        var paths = new EnvironmentPathResolver();
        var fs = new RealFileSystemAccess();

        // Single-instance mutex.
        using var guard = BuildSingleInstanceGuard(parsed);
        if (guard is null)
        {
            // A second copy is already running. Wake it up via a
            // named event the running manager polls; otherwise
            // just exit silently.
            TrySignalExistingInstance();
            return 0;
        }

        // Settings store + integrity verifier. The integrity
        // resource is generated by the build pipeline; we accept
        // any failure here as a hard stop because a missing
        // integrity resource is a packaging fault.
        var settingsStore = new JsonSettingsStore(paths, fs);
        var settings = settingsStore.Load();

        IIntegrityVerifier verifier;
        try
        {
            verifier = IntegrityVerifier.FromEmbedded(
                typeof(Program).Assembly,
                "VibertemisManager.App.Resources.Integrity.integrity.json",
                paths.ProgramsRoot);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"Integrity manifest missing or invalid: {ex.Message}\n\nThe installation is corrupt; please reinstall.",
                "Vibertemis Host Manager",
                MessageBoxButtons.OK,
                MessageBoxIcon.Error);
            return 2;
        }

        // Wire up Core services. Windows-only bindings live in
        // the Windows TFM; on other TFMs the App project is not
        // built so this path is Windows-only at compile time.
#if WINDOWS
        var registry = new VibertemisManager.Core.Platform.Windows.WindowsRegistryAccess();
        var autoStart = new VibertemisManager.Core.Platform.Windows.WindowsAutoStartRegistrar();
        var uac = new VibertemisManager.Core.Platform.Windows.ShellExecuteUacHelper();
        var firewallScanner = new VibertemisManager.Core.Platform.Windows.NetshFirewallScanner();
        var processTable = new VibertemisManager.Core.Platform.Windows.WindowsProcessTable();
#else
        IRegistryAccess registry = new FallbackRegistry();
        IAutoStartRegistrarEx autoStart = new NoOpAutoStart();
        IUacHelper uac = new NoOpUac();
        IFirewallScanner firewallScanner = new FallbackFirewallScanner();
        IProcessTable processTable = new VibertemisManager.Core.Platform.Posix.PosixProcessTable();
#endif

        var adapterEnum = new SystemAdapterEnumerator();
        var steam = new RegistrySteamLocator(registry);
        var steamVr = new VrpathSteamVrLocator(paths, fs, steam);
        var alvrLocator = new DefaultAlvrSessionLocator(paths, fs);
        var alvrSettings = new JsonAlvrSettingsReader(fs);
        var busyChecker = new ProcessTableDashboardBusyChecker(processTable);
        var companion = new CompanionRunner(new DefaultProcessLauncher());
        var exportRunner = new CompanionPairingExportRunner();
        var firewallAdapter = new ScannerFirewallAdapter(firewallScanner);
        var singleInstance = new WindowsSingleInstanceGuardFactory();

        var services = new AppServices(
            Paths: paths,
            FileSystem: fs,
            SettingsStore: settingsStore,
            IntegrityVerifier: verifier,
            Registry: registry,
            AutoStart: autoStart,
            UacHelper: uac,
            FirewallScanner: firewallScanner,
            FirewallAdapter: firewallAdapter,
            ProcessTable: processTable,
            Adapters: adapterEnum,
            Steam: steam,
            SteamVr: steamVr,
            AlvrLocator: alvrLocator,
            AlvrSettings: alvrSettings,
            BusyChecker: busyChecker,
            Companion: companion,
            PairingExport: exportRunner,
            SingleInstance: singleInstance);

        using var form = new MainForm(services, parsed);
        if (parsed.TrayOnly || parsed.Silent)
            Application.Run(new ApplicationContext(form));
        else
            Application.Run(form);
        return 0;
    }

    private static int RunApplyUpdate(string jobPath)
    {
        // The worker never acquires the app mutex. It
        // runs with the assembly's TFM-appropriate entry point and
        // avoids touching anything that would interfere with the
        // installer's BusyReason check or the running manager.
        try
        {
            var paths = new EnvironmentPathResolver();
            var env = new WindowsUpdateEnvironment();
            var worker = new UpdateWorker(env, SignedRelease.EmbeddedPublicKey(), paths.UpdateCacheDir);
            var outcomePath = DefaultOutcomePath();
            var inputs = UpdateJobInputs.For(jobPath, paths.UpdateCacheDir, env.CurrentExecutablePath);
            var result = worker.Run(inputs, outcomePath);
            if (!result.Outcome.IsSuccess && result.InstallerLaunched && result.RestartedPid is null)
                MessageBox.Show("The update could not finish and the manager could not reopen.\n\n" + result.Outcome.Detail
                    + "\n\nOpen VibertemisVR Host Manager again, or run the release installer manually.\nInstaller log: " + result.Outcome.InstallerLogPath,
                    "Vibertemis update needs attention", MessageBoxButtons.OK, MessageBoxIcon.Error);
            return result.Outcome.IsSuccess ? 0 : 1;
        }
        catch (Exception ex)
        {
            try
            {
                var fallback = new UpdateOutcome(
                    Schema: UpdateOutcome.CurrentSchema,
                    ExpectedVersion: "",
                    PreviousVersion: SignedRelease.CurrentVersion,
                    Kind: UpdateOutcomeKind.WorkerError,
                    InstallerExitCode: null,
                    InstalledFileVersion: null,
                    VerifyInstallExitCode: null,
                    InstallerLogPath: "",
                    Detail: ex.Message,
                    Timestamp: DateTime.UtcNow);
                Directory.CreateDirectory(Path.GetDirectoryName(DefaultOutcomePath())!);
                File.WriteAllText(DefaultOutcomePath(), fallback.Serialize());
            }
            catch { }
            return 1;
        }
    }

    public static string DefaultOutcomePath()
    {
        var local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        return Path.Combine(local, "VibertemisVRHostManager", "updates", "last-update.json");
    }

    private static string? TryFindArgValue(string[] args, string key)
    {
        for (var i = 0; i < args.Length - 1; i++)
            if (string.Equals(args[i], key, StringComparison.Ordinal))
                return args[i + 1];
        return null;
    }

    private static IDisposable? BuildSingleInstanceGuard(CliArgs args)
    {
#if WINDOWS
        var factory = new WindowsSingleInstanceGuardFactory();
        var guard = factory.Create(MutexName);
        if (!guard.TryAcquire(out var handle))
            return null;
        return handle;
#else
        return new AlwaysAcquiresSingleInstanceGuard();
#endif
    }

    private static void TrySignalExistingInstance(bool shutdown = false)
    {
#if WINDOWS
        try
        {
            // The named event the running manager created is
            // already named; open it and set to signal.
            using var ev = new EventWaitHandle(false, EventResetMode.AutoReset, MutexName + (shutdown ? "-Shutdown" : "-Wake"));
            ev.Set();
        }
        catch { /* running manager will not surface */ }
#endif
    }

}

public sealed record CliArgs(bool TrayOnly, bool Silent, string? ApplyUpdateJob)
{
    public static CliArgs Parse(string[] argv)
    {
        var apply = TryFindArg(argv, "--apply-update");
        return new(
            Array.Exists(argv, a => a == "--tray-only"),
            Array.Exists(argv, a => a == "--silent"),
            apply);
    }

    private static string? TryFindArg(string[] argv, string key)
    {
        for (var i = 0; i < argv.Length - 1; i++)
            if (string.Equals(argv[i], key, StringComparison.Ordinal)) return argv[i + 1];
        return null;
    }
}

public sealed record AppServices(
    IPathResolver Paths,
    IFileSystemAccess FileSystem,
    ISettingsStore SettingsStore,
    IIntegrityVerifier IntegrityVerifier,
    IRegistryAccess Registry,
    IAutoStartRegistrarEx AutoStart,
    IUacHelper UacHelper,
    IFirewallScanner FirewallScanner,
    IFirewallScannerEx FirewallAdapter,
    IProcessTable ProcessTable,
    IAdapterEnumerator Adapters,
    ISteamLocator Steam,
    ISteamVrLocator SteamVr,
    IAlvrSessionLocator AlvrLocator,
    IAlvrSettingsReader AlvrSettings,
    IDashboardBusyChecker BusyChecker,
    ICompanionRunner Companion,
    IPairingExportRunner PairingExport,
    ISingleInstanceGuardFactory SingleInstance);